version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
        exclude-patterns: ["actions/create-github-app-token", "dependabot/fetch-metadata"]
